server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT
    username: root
    password: dyg20010701
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.camellia.entity